### ISSUE TITLE
Tracking MVP version for Todos demo

### ISSUE THREAD

**Issue by M-Adoo** [RibirX/Ribir#42]
- [x] Stateless and stateful widget
  - [x] field state change bind
- [x] refactor render layout
  - [x] render object trait
  - [x] Render Context #39 
- [x] widgets
  - [x] flex
  - [x] row / column
  - [x] SizedBox
  - [x] margin #52 
  - [x] padding #52 
  - [x] background #57 
  - [x] border #57 
  - [x] border radius #57 
  - [x] theme widget #31 
  - [x] text
  - [x] focus #48 
  - [x] input #51 
  - [x] keyboard #50 
  - [x] event support, pointer #36 
  - [x] click, double click 
  - [x] enter/leave #44 
  - [x] cursor #45 
  - [x] Input
  - [x] ListView
  - [x] Icon
  - [x] declare syntax
    - [x] nested struct and data flows. 
    - [x] animation syntax
